name = "corsx"
main = "worker.ts"
compatibility_date = "2024-01-01"

rules = [
  { type = "Text", globs = ["**/*.html"], fallthrough = false }
]



# Uncomment to add a custom domain
# routes = [
#   { pattern = "corsx.yourdomain.com", custom_domain = true }
# ]

# Uncomment if you add KV for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "4209a5dc4cfc484e9843dd1087f1b720"